language: php

sudo: false

pip:
  - 5.5

cache:
  apt: true

  directories:
  - $HOME/.cache/pip
  - $HOME/download

addons:
  apt:
    packages:
    - python-pip
    - python-virtualenv

install: source pip-install.sh
